spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  mail:
    host: localhost
    port: 1025
    username: mcan
    password: mcan
    properties:
      mail:
        smtp:
          trust:"*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: MAHSEVMAHSEVMAHSEVMAHSEVMAHSEVMAHSEVMAHSEVMAHSEVMAHSEVMAHSEV
      expiration: 8640000
